# Generated by Django 5.2 on 2025-04-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobTech', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default=0, max_length=255, verbose_name='Job Location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='remote',
            field=models.CharField(choices=[('remote', 'Fully Remote'), ('Hybrid', 'Partially Remote'), ('On-site', 'Office Based')], default='office', max_length=20, verbose_name='Remote Work Option'),
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salary Amount'),
        ),
        migrations.AlterField(
            model_name='job',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Posting Date'),
        ),
        migrations.AlterField(
            model_name='job',
            name='desc',
            field=models.TextField(help_text='Detailed job description', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='job',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='job_images/', verbose_name='Job Image'),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=75, verbose_name='Job Title'),
        ),
    ]
