# Generated by Django 5.2 on 2025-04-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobTech', '0002_job_location_job_remote_job_salary_alter_job_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='salary',
            new_name='MaxSalary',
        ),
        migrations.AddField(
            model_name='job',
            name='MinSalary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salary Amount'),
        ),
        migrations.AlterField(
            model_name='job',
            name='remote',
            field=models.CharField(choices=[('remote', 'Fully Remote'), ('Hybrid', 'Partially Remote'), ('OnSite', 'Office Based')], default='office', max_length=20, verbose_name='Remote Work Option'),
        ),
    ]
