# Generated by Django 5.2 on 2025-04-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobTech', '0003_rename_salary_job_maxsalary_job_minsalary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('M', 'Marketing'), ('CS', 'Customer Service'), ('HR', 'Human Resource'), ('PM', 'Project Management'), ('BD', 'Business Development '), ('S&C', 'Sales & Communication'), ('T&E', 'Teaching & Education'), ('D&C', 'Design & Creative')], default='office', max_length=20, verbose_name='Remote Work Option'),
        ),
    ]
