# Generated by Django 5.2 on 2025-04-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobTech', '0004_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='MaxSalary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Max Salary Amount'),
        ),
        migrations.AlterField(
            model_name='job',
            name='MinSalary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Min Salary '),
        ),
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('IT', 'IT Services & Consulting'), ('M', 'Marketing'), ('CS', 'Customer Service'), ('HR', 'Human Resource'), ('PM', 'Project Management'), ('BD', 'Business Development '), ('S&C', 'Sales & Communication'), ('T&E', 'Teaching & Education'), ('D&C', 'Design & Creative')], default='office', max_length=20, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='job',
            name='remote',
            field=models.CharField(choices=[('R', 'Fully Remote'), ('H', 'Partially Remote'), ('OS', 'Office Based')], default='office', max_length=20, verbose_name='Remote Work Option'),
        ),
    ]
