# Generated by Django 5.2 on 2025-04-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobTech', '0005_alter_job_maxsalary_alter_job_minsalary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='img',
            field=models.ImageField(blank=True, default='fallback.png', null=True, upload_to='', verbose_name='Job Image'),
        ),
    ]
