# Generated by Django 5.2 on 2025-04-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobTech', '0006_alter_job_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='desc',
        ),
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed job description', null=True, verbose_name='Job Description'),
        ),
        migrations.AddField(
            model_name='job',
            name='qualifications',
            field=models.TextField(blank=True, help_text='Detailed job qualifications', null=True, verbose_name='Job Qualifications '),
        ),
        migrations.AddField(
            model_name='job',
            name='responsibility',
            field=models.TextField(blank=True, help_text='Detailed job responsibilities', null=True, verbose_name='Job Responsibility '),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='Job Title'),
        ),
    ]
