# Generated by Django 5.2 on 2025-04-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobTech', '0007_remove_job_desc_job_description_job_qualifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('IT Services & Consulting', 'IT Services & Consulting'), ('Marketing', 'Marketing'), ('Customer Service', 'Customer Service'), ('Human Resource', 'Human Resource'), ('Project Management', 'Project Management'), ('Business Development', 'Business Development '), ('Sales & Communication', 'Sales & Communication'), ('Teaching & Education', 'Teaching & Education'), ('Design & Creative', 'Design & Creative')], default='office', max_length=75, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='job',
            name='remote',
            field=models.CharField(choices=[('Remote', 'Fully Remote'), ('Hybrid', 'Partially Remote'), ('On Site', 'Office Based')], default='office', max_length=20, verbose_name='Remote Work Option'),
        ),
    ]
